
datasets:
  crocus_qa:
    # data_dir: ${env.data_dir}/datasets
    data_type: features # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      splits: ["train", "val"]  # val
      storage: /data/EECS-MachineListeningLab/datasets/LLaqo/crocus
