# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: instruct_vicuna7b
  load_finetuned: True
  load_pretrained: False

  pretrained: "/data/EECS-MachineListeningLab/huan/lam/check_point/Pretrain_stage1/20230829080/checkpoint_63700.pth"
  finetuned: "/data/EECS-MachineListeningLab/huan/lam/check_point/Pretrain_stage2/20230914144/checkpoint_270000.pth" # "/data/EECS-MachineListeningLab/huan/lam/check_point/Pretrain_stage2/20230913011/checkpoint_90000.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # path to Vicuna checkpoint
  llm_model: "/data/EECS-MachineListeningLab/huan/hf_cache/hub/models--lmsys--vicuna-7b-v1.5/snapshots/de56c35b1763eaae20f4d60efd64af0a9091ebe5"

  # generation configs
  prompt: ""
  qformer_text_input: True

preprocess:
  vis_processor:
    train:
      name: "blip2_image_train"
      image_size: 224
    eval:
      name: "blip_image_eval"
      image_size: 224

  text_processor:
    train:
      name: "blip_caption"
    eval:
      name: "blip_caption"
